<?php /**
 * @category    AJH
 * @package     AJH_Fitment
 * @copyright   Copyright (c) 2018-2019
 */ ?>

<div class="container mt-4 mb-1">
    <div class="row mb-2">
        <div class="fitment_wrapper col-12 col-md-12 px-0">
            <div class="d-md-flex bd-highlight">
                <div class="select-fitment-label-wrap">
                    <h3 class="select-fitment-label d-lg-flex px-3">
                        <i class="fa fa-car fitment-label-icon pr-1" aria-hidden="true"></i>
                        <span class="shop-by-vehicle title">Shop by vehicle</span>
                        <i class="fa fa-angle-right d-md-none fitment-label-direction" aria-hidden="true"></i>
                    </h3>
                </div>
                <div class="fitment-main-wrap d-md-flex px-2 mt-1 px-md-0 mt-md-0">
                    <div class="yemamosu-wrap d-md-flex">                        
                        <div class="year-wrapper">
                            <select name="year" id="fitment_year" disabled="disabled">
                                <option>Year</option>
                                <?php /*foreach ($years as $year): ?>
                                    <?php $data = $year->getData(); ?>
                                    <option value="<?php echo $data['YearID']; ?>"><?php echo $data['YearID']; ?></option>
                                <?php endforeach; */ ?>
                            </select>
                        </div>
                        <div class="make-wrapper">
                            <select name="make" id="fitment_make" disabled="disabled">
                                <option>Make</option>
                                <option>-</option>
                            </select>
                        </div>
                        <div class="model-wrapper">
                            <select name="model" id="fitment_model" disabled="disabled">
                                <option>Model</option>
                                <option>-</option>
                            </select>
                        </div>
                        <div class="submodel-wrapper">
                            <select name="submodel" id="fitment_submodel" disabled="disabled">
                                <option>SubModel</option>
                                <option>-</option>
                            </select>
                        </div>
                        <div id="qualifier_wrap"></div>
                    </div>                    
                    <div class="fitment-action">
                        <button type="button" class="button btn-success" id="fitment_parts">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php
$ajaxurl = json_decode($block->getFitmentUrls());

$garage_ajaxurl = $block->getUrl('fitment/garage/index');
$remove_ajaxurl = $block->getUrl('fitment/garage/removevehicle');
?>

<script type="text/x-magento-init">
    {
    "*": {
    "AJH_Fitment/js/fitmentajax": {
    "AjaxUrl": "<?php echo $ajaxurl->index; ?>",
    "yearsUrl": "<?php echo $ajaxurl->years; ?>",
    "makesUrl": "<?php echo $ajaxurl->makes; ?>",
    "modelsUrl": "<?php echo $ajaxurl->models; ?>",
    "submodelsUrl": "<?php echo $ajaxurl->submodels; ?>",
    "qualifiersUrl": "<?php echo $ajaxurl->qualifiers; ?>",
    "categoriesUrl": "<?php echo $ajaxurl->categories; ?>",
    "StoreUrl": "<?php echo $block->getBaseUrl(); ?>"
    },
    "garagejs":{                
    "AjaxUrl": "<?php echo $garage_ajaxurl; ?>",
    "GarageUrl": "<?php echo $remove_ajaxurl; ?>"
    }
    }
    }
</script>
<script type="text/javascript">

//    function loadFitmentCategories(ths) {
//        if (ths.value !== "") {
//            var location = "<?php echo $this->getUrl('fitment/index/categories') . "?" ?>" + ths.value;
//            window.location = location;
//        }
//    }
//
//    function setAjaxData(data, iframe) {
//        if (data.status === 'ERROR') {
//            // alert(data.message);
//        } else {
//            if (jQuery('.block-cart')) {
//                jQuery('.block-cart').replaceWith(data.sidebar);
//            }
//            if (jQuery('.header .links')) {
//                jQuery('.header .links').replaceWith(data.toplink);
//            }
//            jQuery.fancybox.close();
//        }
//    }
//    function setLocationAjax(url, id) {
//        url += 'isAjax/1';
//        url = url.replace("checkout/cart", "ajaxcart/index");
//
//        jQuery('#ajax_loader').show();
//        try {
//            jQuery.ajax({
//                cache: false,
//                url: url,
//                dataType: 'json',
//                success: function (data) {
//                    jQuery('#ajax_loader').hide();
//                    if (jQuery('.mini-cart')) {
//                        jQuery('.mini-cart').replaceWith(data.sidebar);
//                    }
//                    if (jQuery('.header .links')) {
//                        jQuery('.header .links').replaceWith(data.toplink);
//                    }
//                }
//            });
//        } catch (e) {
//        }
//    }
</script>