<script>
    require([
        "jquery"
    ], function ($) {
        //your code to send ajax request here
        
        console.log('admin js file');
        
//        $.ajax({
//            showLoader: true,
//            url: "admin/PostaPlus/PostaPlusShipping/HSCodes",
//            data: param,
//            type: "POST",
//            dataType: 'json'
//        }).done(function (data) {
//            alert(data);
//            console.log(data);
//        });
    });
</script>